version: '3.8'
services:
  ollama:
    build:
      context: .
      dockerfile: dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5500:5500"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - FRONTEND_PORT=5500
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 25s

volumes:
  ollama_data:
